### ISSUE TITLE
Problems starting the stream.

### ISSUE THREAD

**Issue by chrisconnelly** [alexandrebarachant/muse-lsl#116]
I've been trying a couple of days to understand why my install of muselsl just isn't working. I installed using pip, on Anaconda and either using the Juptyer notebook or Anaconda prompt I get the following report when I try to stream:

(base) C:\Users\Chris>muselsl stream -n Muse-1828
Starting BlueMuse, see BlueMuse window for interactive list of devices.
Traceback (most recent call last):
  File "c:\users\chris\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chris\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chris\Anaconda3\Scripts\muselsl.exe\__main__.py", line 9, in <module>
  File "c:\users\chris\anaconda3\lib\site-packages\muselsl\__main__.py", line 57, in main
    cli = CLI(args.command)
  File "c:\users\chris\anaconda3\lib\site-packages\muselsl\cli.py", line 9, in __init__
    getattr(self, command)()
  File "c:\users\chris\anaconda3\lib\site-packages\muselsl\cli.py", line 51, in stream
    args.interface, args.name, args.ppg, args.acc, args.gyro, args.disable_eeg)
  File "c:\users\chris\anaconda3\lib\site-packages\muselsl\stream.py", line 66, in stream
    found_muse = find_muse(name)
  File "c:\users\chris\anaconda3\lib\site-packages\muselsl\stream.py", line 54, in find_muse
    for muse in muses:
TypeError: 'NoneType' object is not iterable

When I do $muselsl list, I do get the BlueMuse window which lists correctly the available muses, however if I try to use BlueMuse to start stream it causes the BlueMuse app to close.

Any thoughts?

**Comment by Pensarfeo** [comment]
I solved that one, you need to ad a backend flag
Try:
muselsl stream -n Muse-1828 --backend bluemuse
