### ISSUE TITLE
ModuleNotFoundError: No module named 'bitstring'

### ISSUE THREAD

**Issue by luzpaz** [alexandrebarachant/muse-lsl#12]
Problem:
```
$ python3 muse-lsl.py
Traceback (most recent call last):
  File "muse-lsl.py", line 1, in <module>
    from muse import Muse
  File "/home/b/Projects/muse/muse-lsl/muse/__init__.py", line 1, in <module>
    from .muse import Muse
  File "/home/b/Projects/muse/muse-lsl/muse/muse.py", line 1, in <module>
    import bitstring
ModuleNotFoundError: No module named 'bitstring'
```
Muse 2016
Python3:
```
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
```
Machine Specs:
```
System:   Kernel: 4.9.47-1-MANJARO x86_64 (64 bit gcc: 7.1.1) Desktop: Xfce 4.12.4 (Gtk 2.24.31)
           Distro: Manjaro Linux
Machine:   Device: laptop System: Dell product: XPS 13 9350
           Mobo: Dell model: 09JHRY v: A00 UEFI: Dell v: 1.4.18 date: 06/06/2017
Battery    BAT0: charge: 15.7 Wh 22.2% condition: 70.8/75.7 Wh (94%) model: SMP DELL JHXPY53 status: Discharging
CPU:       Dual core Intel Core i7-6560U (Skylake rev.3) (-HT-MCP-) cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 8834
           clock speeds: max: 3200 MHz 1: 1799 MHz 2: 1799 MHz 3: 1799 MHz 4: 1578 MHz
Graphics:  Card: Intel Iris Graphics 540 bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.3) driver: intel Resolution: 1280x720@60.00hz
           OpenGL: renderer: Mesa DRI Intel Iris Graphics 540 (Skylake GT3e)
           version: 4.5 Mesa 17.1.8 Direct Render: Yes
Audio:     Card Intel Sunrise Point-LP HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.9.47-1-MANJARO
Network:   Card: Broadcom Limited BCM4350 802.11ac Wireless Network Adapter driver: brcmfmac bus-ID: 3a:00.0
           IF: wlp58s0 state: up mac: <filter>
Drives:    HDD Total Size: NA (-)
           ID-1: /dev/nvme0n1 model: N/A size: 512.1GB
Partition: ID-1: / size: 452G used: 25G (6%) fs: ext4 dev: /dev/nvme0n1p2
           ID-2: swap-1 size: 18.34GB used: 0.00GB (0%) fs: swap dev: /dev/nvme0n1p3
Info:      Processes: 208 Uptime: 3:25 Memory: 3537.6/15898.0MB Init: systemd Gcc sys: 7.1.1
           Client: Shell (bash 4.4.121) inxi: 2.3.27
```

**Comment by luzpaz** [comment]
duh, i needed to install it via pip:
`pip install bitstring`
