### ISSUE TITLE
Cannot view when streaming PPG ACC GYRO

### ISSUE THREAD

**Issue by danielemarinazzo** [alexandrebarachant/muse-lsl#161]
Hi

I am on Ubuntu 18.04.

When I just stream EEG, I can correctly view it in another terminal.

If on the other hand I stream also PPG, AAG, and GYRO, I get

`Streaming EEG PPG ACC GYRO...
`
but when I run `muselsl view` on the other terminal I get

```
Looking for an EEG stream...
Traceback (most recent call last):
  File "/home/daniele/anaconda3/envs/muse_env/bin/muselsl", line 8, in <module>
    sys.exit(main())
  File "/home/daniele/anaconda3/envs/muse_env/lib/python3.8/site-packages/muselsl/__main__.py", line 57, in main
    cli = CLI(args.command)
  File "/home/daniele/anaconda3/envs/muse_env/lib/python3.8/site-packages/muselsl/cli.py", line 9, in __init__
    getattr(self, command)()
  File "/home/daniele/anaconda3/envs/muse_env/lib/python3.8/site-packages/muselsl/cli.py", line 121, in view
    view(args.window, args.scale, args.refresh,
  File "/home/daniele/anaconda3/envs/muse_env/lib/python3.8/site-packages/muselsl/view.py", line 8, in view
    viewer_v1.view(window, scale, refresh, figure, backend)
  File "/home/daniele/anaconda3/envs/muse_env/lib/python3.8/site-packages/muselsl/viewer_v1.py", line 21, in view
    raise(RuntimeError("Can't find EEG stream."))
RuntimeError: Can't find EEG stream.
```

**Comment by buyuk-dev** [comment]
Are you sure the stream was running while you started the view command?
If you are sure the stream wasn't closed accidentally, try increasing the timeout. I've had an instance of this error when for some reason it took the resolve_byprop() function call longer than usual to resolve the stream.
