### ISSUE TITLE
ERROR on Windows 10 20H2 and python 3.10.

### ISSUE THREAD

**Issue by Zibri** [alexandrebarachant/muse-lsl#176]
```
C:\WINDOWS\system32>python -m muselsl stream
Searching for Muses, this may take up to 10 seconds...
Found device Muse-E133, MAC Address 00:55:DA:B0:E1:33
2022-03-21 20:46:39.878 (  11.320s) [        53DA8980]         api_config.cpp:231   INFO| Loaded default config
2022-03-21 20:46:39.879 (  11.321s) [        53DA8980]             common.cpp:64    INFO| git:a0fc2fde92a10f4cb5fccbc5552228b865f17379/branch:refs/tags/v1.15.0/build:Release/compiler:MSVC-19.0.24245.0/link:SHARED
2022-03-21 20:46:39.883 (  11.325s) [        53DA8980] stream_outlet_impl.cpp:88    WARN| Couldn't create multicast responder for 224.0.0.1 (set_option: A socket operation was attempted to an unreachable host)
Connecting to Muse-E133: 00:55:DA:B0:E1:33...
Traceback (most recent call last):
  File "C:\Users\Zibri\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zibri\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

```
this instead works:
```
C:\>python -m muselsl record_direct
Searching for Muses, this may take up to 10 seconds...
Found device Muse-E133, MAC Address 00:55:DA:B0:E1:33
Connecting to Muse-E133 : 00:55:DA:B0:E1:33...
Connecting to Muse: 00:55:DA:B0:E1:33...
Start recording at time t=1647888538.976
Done - wrote file: C:\recording_2022-03-21-18.48.50.csv.


```

This is the culprit:
`2022-03-21 20:46:39.883 (  11.325s) [        53DA8980] stream_outlet_impl.cpp:88    WARN| Couldn't create multicast responder for 224.0.0.1 (set_option: A socket operation was attempted to an unreachable host)
`

For reference:
```
C:\WINDOWS\system32>route print
===========================================================================
Interface List
 24...9c b6 d0 08 36 95 ......Killer Wireless-n/a/ac 1535 Wireless Network Adapter
 10...9e b6 d0 08 36 95 ......Microsoft Wi-Fi Direct Virtual Adapter #4
 16...ae b6 d0 08 36 95 ......Microsoft Wi-Fi Direct Virtual Adapter #5
  8...d8 cb 8a f3 7d 71 ......Killer E2400 Gigabit Ethernet Controller
  7...9c b6 d0 08 36 96 ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1    192.168.1.119     35
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      192.168.1.0    255.255.255.0         On-link     192.168.1.119    291
    192.168.1.119  255.255.255.255         On-link     192.168.1.119    291
    192.168.1.255  255.255.255.255         On-link     192.168.1.119    291
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link     192.168.1.119    291
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link     192.168.1.119    291
===========================================================================
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
  1    331 ::1/128                  On-link
  1    331 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None

C:\WINDOWS\system32>
```

**Comment by Zibri** [comment]
P.S.
The headband works perfectly.
The problem seems to be in python listening part.
record_direct works.

**Comment by Zibri** [comment]
I have no idea what happened.
Now it works.

![image](https://user-images.githubusercontent.com/855176/159597212-eb838f0e-af67-43b8-9659-7947b638ac3b.png)

Maybe it has to do to the fact I have found and installe Muse Direct too...

**Comment by jdpigeon** [comment]
It looks like there was some issue with the way the LSL library interacted with your network environment.

I'm glad to hear things seem to be working now!
