### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by JaimeAlHerr** [alexandrebarachant/muse-lsl#205]
I'm having some trouble with the connection to my MUSE, the thing is that my PC detects the headband but when it tries to connect it doesn't work. The appearing error is this one:
2023-11-09 08:21:46.925 (   0.900s) [         A4EF474]      netinterfaces.cpp:36    INFO| netif '{F95C780A-EB58-4677-90D9-E097E2286D51}' (status: 1, multicast: 1
2023-11-09 08:21:46.926 (   0.900s) [         A4EF474]      netinterfaces.cpp:58    INFO|                                                                  IPv6 ifindex 19
2023-11-09 08:21:46.926 (   0.901s) [         A4EF474]      netinterfaces.cpp:36    INFO| netif '{63484605-EF8D-427D-9457-AC4CFE7A41B0}' (status: 1, multicast: 1
2023-11-09 08:21:46.927 (   0.901s) [         A4EF474]      netinterfaces.cpp:58    INFO|                                                                  IPv6 ifindex 10
2023-11-09 08:21:46.927 (   0.901s) [         A4EF474]      netinterfaces.cpp:36    INFO| netif '{4B2D1851-7DCE-448F-895D-7884E166D50E}' (status: 2, multicast: 1
2023-11-09 08:21:46.927 (   0.901s) [         A4EF474]      netinterfaces.cpp:36    INFO| netif '{F96244D5-40F6-11EE-BDD6-806E6F6E6963}' (status: 1, multicast: 1
2023-11-09 08:21:46.927 (   0.902s) [         A4EF474]      netinterfaces.cpp:58    INFO|                                                                  IPv6 ifindex 1
2023-11-09 08:21:46.928 (   0.902s) [         A4EF474]      netinterfaces.cpp:36    INFO| netif '{6ED5CB35-F7C4-4455-AE10-6F92F6DAD01B}' (status: 1, multicast: 1
2023-11-09 08:21:46.928 (   0.902s) [         A4EF474]      netinterfaces.cpp:58    INFO|                                                                  IPv6 ifindex 20
2023-11-09 08:21:46.928 (   0.902s) [         A4EF474]         api_config.cpp:270   INFO| Loaded default config
2023-11-09 08:21:46.928 (   0.903s) [         A4EF474]             common.cpp:65    INFO| git:6dc417089a1f73f26589b4f1e64def357b183e9c/branch:refs/tags/v1.16.1/build:Release/compiler:MSVC-19.0.24245.0/link:SHARED
2023-11-09 08:21:46.951 (   0.926s) [         A4EF474]         udp_server.cpp:82    WARN| Could not bind multicast responder for ff02:113d:6fdd:2c17:a643:ffe2:1bd1:3cd2 to interface ::1 (Se ha proporcionado un argumento no vßlido.)
2023-11-09 08:21:46.952 (   0.926s) [         A4EF474]         udp_server.cpp:82    WARN| Could not bind multicast responder for ff02:113d:6fdd:2c17:a643:ffe2:1bd1:3cd2 to interface 172.21.112.1 (Se ha proporcionado un argumento no vßlido.)
2023-11-09 08:21:46.953 (   0.927s) [         A4EF474]         udp_server.cpp:82    WARN| Could not bind multicast responder for ff05:113d:6fdd:2c17:a643:ffe2:1bd1:3cd2 to interface ::1 (Se ha proporcionado un argumento no vßlido.)
2023-11-09 08:21:46.953 (   0.927s) [         A4EF474]         udp_server.cpp:82    WARN| Could not bind multicast responder for ff05:113d:6fdd:2c17:a643:ffe2:1bd1:3cd2 to interface 172.21.112.1 (Se ha proporcionado un argumento no vßlido.)
Connecting to Muse: 00:55:DA:B3:2A:E5...
Traceback (most recent call last):
  File "c:\Users\PVR1\Desktop\Residencias\Python\examples\neurofeedback.py", line 62, in <module>
    stream('00:55:DA:B3:2A:E5')
  File "C:\Users\PVR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\muselsl\stream.py", line 221, in stream
    didConnect = muse.connect()
                 ^^^^^^^^^^^^^^
  File "C:\Users\PVR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\muselsl\muse.py", line 84, in connect
    self.device = self.adapter.connect(self.address)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PVR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\muselsl\backends.py", line 37, in connect
    result.connect()
  File "C:\Users\PVR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\muselsl\backends.py", line 45, in connect
    _wait(self._client.connect())
  File "C:\Users\PVR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\muselsl\backends.py", line 11, in _wait
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PVR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bleak\backends\winrt\client.py", line 205, in connect
    raise BleakError(f"Device with address {self.address} was not found.")
bleak.exc.BleakError: Device with address 00:55:DA:B3:2A:E5 was not found.

**Comment by Neuroera** [comment]
Is bled112 needed to connect Muse 2016 with Windows 10? where can I get it? thanks
